import {chromium} from '/nvme/development/polyorama/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
const b=await chromium.connectOverCDP('http://127.0.0.1:9328');
const p=b.contexts()[0].pages()[0];
const root=process.cwd()+'/target/bokkie-tmp/root-a', special='nested/space 日本 %?#.md';
const url=(r,page)=>`http://127.0.0.1:3828/#workspace=${encodeURIComponent(r)}&page=${encodeURIComponent(page)}`;
const wait=async(page,r=root)=>{await p.waitForFunction(({page,r})=>window.pagefoldObservation?.().page===page&&pagefoldObservation().root===r&&!pagefoldObservation().pending,{page,r});await p.waitForTimeout(150);};
const click=async id=>{const n=await p.evaluate(id=>pagefoldObservation().nodes.find(n=>n.id===id),id);await p.mouse.click(n.rect[0]+n.rect[2]/2,n.rect[1]+n.rect[3]/2);};
await p.goto(url(root,special));await p.reload();await wait(special);
await click('page:A.md');await wait('A.md');assert.equal(p.url(),url(root,'A.md'));
await p.goBack();await wait(special);
await click('pagefold.forward');await wait('A.md');assert.equal(p.url(),url(root,'A.md'));
await p.reload();await wait('A.md');
await p.goto(url(root,'Missing.md'));await wait('Missing.md');
await p.goto(url(root+'/absent','A.md'));await p.waitForFunction(()=>pagefoldObservation().status.includes('Unable to read workspace'));
await p.goto(url(root,'../B.md'));await p.waitForFunction(()=>pagefoldObservation().status.includes('Invalid page link'));
await p.goto(url(root.replace('root-a','root-b'),'B.md'));await wait('B.md',root.replace('root-a','root-b'));
await p.goto(url(root,special));await wait(special);
console.log(JSON.stringify({pass:true,cases:['special fresh URL','list address','browser Back','app Forward','reload','missing page','missing root','traversal rejection','workspace isolation'],url:p.url()}));
await b.close();
